### ISSUE TITLE
Failed to execute 'postMessage'

### ISSUE THREAD

**Issue by niklasf** [niklasf/stockfish.wasm#7]
```
lichess.site.min.js:26 Lichess is open source! github.com/ornicar/lila
lichess.analyse.min.js:1 watchdog armed: wasmx
stockfish.js:12 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': #<Module> could not be cloned.
at Object.allocateUnusedWorkers (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:31359)
at lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18291
at callRuntimeCallbacks (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:15739)
at preRun (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:16381)
at run (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146940)
at runCaller (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146186)
at removeRunDependency (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18062)
at receiveInstance (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:20807)
at receiveInstantiatedSource (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:21128)
lichess.site.min.js:7 The Web Audio autoplay policy will be re-enabled in Chrome 71 (December 2018). Please check that your website is compatible with it. goo.gl/7K7WLu
s @ lichess.site.min.js:7
stockfish.js:12 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': #<Module> could not be cloned.
at Object.allocateUnusedWorkers (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:31359)
at lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18291
at callRuntimeCallbacks (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:15739)
at preRun (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:16381)
at run (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146940)
at runCaller (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146186)
at removeRunDependency (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18062)
at receiveInstance (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:20807)
at receiveInstantiatedSource (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:21128)
lichess.analyse.min.js:1 watchdog disarmed: wasmx
stockfish.js:12 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': #<Module> could not be cloned.
at Object.allocateUnusedWorkers (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:31359)
at lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18291
at callRuntimeCallbacks (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:15739)
at preRun (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:16381)
at run (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146940)
at runCaller (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146186)
at removeRunDependency (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18062)
at receiveInstance (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:20807)
at receiveInstantiatedSource (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:21128)
stockfish.js:12 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': #<Module> could not be cloned.
at Object.allocateUnusedWorkers (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:31359)
at lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18291
at callRuntimeCallbacks (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:15739)
at preRun (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:16381)
at run (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146940)
at runCaller (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:146186)
at removeRunDependency (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:18062)
at receiveInstance (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:20807)
at receiveInstantiatedSource (lichess.org/assets/_UcLLmA/vendor/stockfish.wasm/stockfish.js:12:21128)
```

**Comment by niklasf** [comment]
https://lichess.org/forum/lichess-feedback/what-happened-to-pnacl-stockfish-in-chrome?page=2#20: Chrome/70.0.3538.67
https://lichess.org/forum/lichess-feedback/what-happened-to-pnacl-stockfish-in-chrome?page=2#15: Chrome 69.0.3497.92
